---
functional:
  - Пользователь должен иметь возможность создать учетную запись используя email
  - Пользователь должен иметь возможность войти в зарегистрированную учетную запись с помощью пары email:passowrd
  - Никнейм должен быть от 3 до 16 символов
  - Никнейм может содержать только латинские буквы, цифры и знак подчеркивания
  - Никнейм должен начинаться только с латинской буквы
  - Длина пароля от 6 до 16 символов
  - Пароль может содержать латинские, кириллические буквы, цифры и спец.символы
  - Пользователь должен иметь возможность авторизоваться на сайте через учетную запись Github
  - Пользователь должен иметь возможность авторизоваться на сайте через учетную запись Discord
  - Пользователь может разлогиниться из своей учетной записи
  - Пользователь должен иметь возможность восстановить пароль от учетной записи
  - Пользователь должен иметь возможность создать новую игру с другим зарегистрированным пользователем, с другом, или с ботом
  - Пользователь может выбрать уроверь сложности игры
  - Пользователь может выбрать ограничение временем на решение одной задачи в диапазоне от 3 минут до 60 минут
  - Пользователь может выбрать название задачи по имени из списка или по тегам
  - Сайт должен создавать игру рандомно если выбран только уровень игры и её тип
  - Пользователь должен иметь возможность выбрать язык программирования для решения задачи
  - Авторизированный пользователь должен иметь возможность написать в чат на главной странице сайте
  - У пользовательа должна быть возможность выйти из режима игры на "домашнюю" страницу
  - Пользователь должен иметь возможность после авторизации просматривать текущие лобби,  соревновая и историю
  - Авторизованный пользователь может присоединиться к любой доступной игре
  - Пользователь может присоединится к игре по ссылке - приглашению
  - Пользователь можем отменить им же созданную игру
  - Пользователь может отказаться от игры с другом по приглашению
  - Одновременно Пользователь может создать только одну игру
  - Пользователь может следить за игрой других участников как гость
  - Пользователь должен иметь возможность просматривать код оппонента в запущенной игре, в режиме реального времени
  - Пользователь должен иметь возможность сбосить написанный им код
  - На сайте, в режиме созданной игры должен отображатся вывод тестов запущенного кода
  - Пользовательи должны иметь возможность обмениваться сообщениями через чат, во время игры
  - Пользователи с premium подпиской должны иметь возможность просматривать историю игр на вкладке History
  - В созданной игре должен отображатся таймер отведенного на игру времени
  - Пользователь должен иметь возможность запустить редактор wim в режиме игры
  - Авторизированный пользователь должен иметь возможность просматривать статистику профиля и список завершенных игр
  - Авторизованный пользователь должен иметь возможность просматривать рейтинг пользователей (общий, за месяц, за неделю)
  - Авторизованный пользователь должен иметь возможность просматривать список всех задач доступных к решению в игре
  - Авторизованный пользователь должен иметь возможность создать свою собственную задачу
  - Авторизованный пользователь должен иметь возможность просматривать таблицу турниров
  - Авторизованный пользователь может просматривать top list пользователей
  - Пользователь должен иметь возможность создать турнир
  - Ползователь может изменить имя аккаунта
  - Пользователь может установить предпочитаемвый язык программирования языком по умолчанию
  - Пользователь может указать команду (клан) в которой он состоит
  - Пользователь может выбрать тип звуковых оповещений
  - Пользователь может устанавливать уровень громкости звуковых оповещений
  - Пользователь может отвязать аккаунт Github  в личном кабинете
  - Пользователь может привязать аккаунт Discord в личном кабинете
  - Пользователь может открыть описание задачи в сплывающем окне
  - Пользователь может выбрать язык описания задачи (RU, EN)
  - Пользователь может сдаться в созданной игре
  - Пользователь должен иметь возможность выйти из игры и вернуться к ней
  - Созданная игра должна завершаться автоматически через задданный интервал времени, если никто из Пользовательов не запустил написанный код
  - Пользователь может начать игру с ботом с главной страницы сайта без регистрации аккаунта
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь адаптивный дизайн для мобильных устройств и планшетов
  - Сайт должен быть совместим с последними версиями браузеров Chrome, Yandex, Edge, Firefox, Safari, Opera
  - Сайт должен быть способен обрабатывать трафик от 1000 пользователей онлайн
  - Редактор кода должен иметь светлую и тёмную темы
  - Редактор кода должен поддерживать подсветку выбранного языка программирования
implicit:
  - Должна быть реализована возможность запуска написанного кода на исполненеие
  - Пользователь должен иметь возможность писать код на выбранном языке программирования
  - Пользователь должен иметь возможность ознакомиться с описанием задачи
  - Пользователи, в роли зрителя, не могут давать подсказки участникам состязания
  - Новый пользователь не может зарегистрироваться если на указанный никнейм, логин или пароль уже была регистрация
  - Пользователь не может списать код у соперника во время игры
  - Пользователь не может изменять свой рейтинг вручную в профиле аккаунта
