---
functional:
  - Пользователь должен иметь возможность создать учетную запись
  - Пользователь должен иметь возможность войти в зарегистрированную учетную запись
  - Пользователь должен иметь возможность восстановить пароль от учетной записи
  - Пользователь должен иметь возможность создать новую игру с другим зарегистрированным пользователем, с другом, или с ботом
  - У ингрока должна быть возможность выбора одного из четырех возможных уровней сложности игры
  - Реализовать ограничение времени на решение одной задачи в диапазоне от 3 минут до 60 минут
  - Игрок должен иметь возможность выбрать название задачи по имени из списка или по тегам
  - Игрок должен иметь возможность выбрать язык программирования для решения задачи
  - Пользователь должен иметь возможность написать сообщение своему оппоненту во время игры
  - У игрока должна быть возможность выйти из режима игры на "домашнюю" страницу
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь адаптивный дизайн для мобильных устройств и планшетов
  - Сайт должен быть совместим с последними версиями браузеров Chrome, Yandex, Edge, Firefox, Safari, Opera
  - Сайт должен быть способен обрабатывать трафик от 1000 пользователей онлайн 
implicit:
  - Должна быть реализована возможность запуска написанного кода на исполненеие
  - Должна быть реализована возможность сброса написанного кода
