---
functional:
  - Пользователь должен иметь возможность создать учетную запись
  - Пользователь должен иметь возможность войти в зарегистрированную учетную запись с помощью пары email:passowrd
  - Пользователь должен иметь возможность авторизоваться на сайте через учетную запись на Github
  - Пользователь должен иметь возможность авторизоваться на сайте через учетную запись Discord
  - Пользователь может разлогиниться из своей учетной записи
  - Пользователь должен иметь возможность восстановить пароль от учетной записи
  - Пользователь должен иметь возможность создать новую игру с другим зарегистрированным пользователем, с другом, или с ботом
  - Пользователь должен иметь возможность создать игру по ссылке-приглашению
  - У ингрока должна быть возможность выбора одного из четырех возможных уровней сложности игры
  - Игрок может выбрать ограничение времени на решение одной задачи в диапазоне от 3 минут до 60 минут
  - Игрок должен иметь возможность выбрать название задачи по имени из списка или по тегам
  - Сайт должен создавать игру рандомно если выбран только уровень игры и её тип
  - Игрок должен иметь возможность выбрать язык программирования для решения задачи
  - Авторизированный пользователь должен иметь возможность написать в чат на главной странице сайте
  - У игрока должна быть возможность выйти из режима игры на "домашнюю" страницу
  - Игрок должен иметь возможность после авторизации просматривать текущие лобби,  соревновая и историю
  - Авторизованный пользователь может присоединиться к любой доступной игре
  - Игрок может присоединится к игре по ссылке - приглашению
  - Пользователь можем отменить им же созданную игру
  - Одновременно игрок может создать только одну игру
  - Пользователь должен иметь возможность просматривать код оппонента в запущенной игре, в режиме реального времени
  - Игрок должен иметь возможность сросить написанный им код
  - На сайте, в режиме активной игры должен отображатся вывод тестов запущенного кода
  - Игроки должны иметь возможность обмениваться сообщениями через чат, во время игры
  - Пользователи с premium подпиской должны иметь возможность просматривать историю игр на вкладке History
  - В созданной игре должен отображатся таймер отведенного на игру времени
  - Пользователь должен иметь возможность запустить редактор wim в режиме игры
  - Авторизированный пользователь должен иметь возможность просматривать статистику профиле и список завершенных игр
  - Авторизованный пользователь должен иметь возможность просматривать рейтинг пользователей (общий, за месяц, за неделю)
  - Авторизованный пользователь должен иметь возможность просматривать список всех задач доступных к решению в игре
  - Авторизованный пользователь должен иметь возможность создать свою собственную задачу
  - Авторизованный пользователь должен иметь возможность просматривать таблицу турниров
  - Пользователь должен иметь возможность создать турнир
  - Ползователь должен иметь возможность изменить имя аккаунта
  - Пользователь должен иметь возможность установить предпочитаемвый язык программирования языком по умолчанию
  - Пользователь должен иметь возможность указать команду в которой он состоит
  - Игрок должен иметь возможность выбрать тип звуковых оповещений
  - Пользователь можем устанавливать уровень громкости звуковых оповещений
  - Пользователь может отвязать аккаунт Github  в личном кабинете
  - Пользователь может привязать аккаунт Discord в личном кабинете
  - Пользователь может открыть описание задачи в сплывающем окне
  - Пользователь может выбрать язык описания задачи (RU, EN)
  - Игрок может сдаться в созданной игре
  - Пользователь должен иметь возможность выйти из игры и вернуться к ней
  - Созданная игра должна завершаться автоматически через задданный интервал времени, если никто из игроков не запустил написанный код
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь адаптивный дизайн для мобильных устройств и планшетов
  - Сайт должен быть совместим с последними версиями браузеров Chrome, Yandex, Edge, Firefox, Safari, Opera
  - Сайт должен быть способен обрабатывать трафик от 1000 пользователей онлайн 
implicit:
  - Должна быть реализована возможность запуска написанного кода на исполненеие
  - Пользователь должен иметь возможность писать код на выбранном языке программирования
  - Пользователь должен иметь возможность ознакомиться с описанием задачи
